name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 21
        uses: actions/setup-java@v4.6.0
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: $GITHUB_WORKSPACE
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
          git config --global init.defaultBranch main
      - name: Build with Maven
        id: build-with-maven
        run: |
          mvn -B package --file pom.xml
          echo "my_jar=$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout).jar" >> $GITHUB_OUTPUT
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.18.0
        if: always()
        with:
          files: |
            target/surefire-reports/**/*.xml
            target/surefire-reports/**/*.trx
            target/surefire-reports/**/*.json
    outputs:
      my_jar: ${{ steps.build-with-maven.outputs.my_jar }}
